server:
	cd ../.. && kitex -module github.com/Yra-A/Fusion_Go idl/favorite.thrift
	kitex -module github.com/Yra-A/Fusion_Go -service FavoriteService -use github.com/Yra-A/Fusion_Go/kitex_gen ../../idl/favorite.thrift
