// Code generated by Kitex v0.7.3. DO NOT EDIT.

package contestservice

import (
	"context"
	contest "github.com/Yra-A/Fusion_Go/kitex_gen/contest"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ContestList(ctx context.Context, req *contest.ContestListRequest, callOptions ...callopt.Option) (r *contest.ContestListResponse, err error)
	ContestInfo(ctx context.Context, req *contest.ContestInfoRequest, callOptions ...callopt.Option) (r *contest.ContestInfoResponse, err error)
	ContestCreate(ctx context.Context, req *contest.ContestCreateRequest, callOptions ...callopt.Option) (r *contest.ContestCreateResponse, err error)
	GetContestsByFavorites(ctx context.Context, req *contest.GetContestsByFavoritesRequest, callOptions ...callopt.Option) (r *contest.GetContestsByFavoritesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kContestServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kContestServiceClient struct {
	*kClient
}

func (p *kContestServiceClient) ContestList(ctx context.Context, req *contest.ContestListRequest, callOptions ...callopt.Option) (r *contest.ContestListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ContestList(ctx, req)
}

func (p *kContestServiceClient) ContestInfo(ctx context.Context, req *contest.ContestInfoRequest, callOptions ...callopt.Option) (r *contest.ContestInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ContestInfo(ctx, req)
}

func (p *kContestServiceClient) ContestCreate(ctx context.Context, req *contest.ContestCreateRequest, callOptions ...callopt.Option) (r *contest.ContestCreateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ContestCreate(ctx, req)
}

func (p *kContestServiceClient) GetContestsByFavorites(ctx context.Context, req *contest.GetContestsByFavoritesRequest, callOptions ...callopt.Option) (r *contest.GetContestsByFavoritesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetContestsByFavorites(ctx, req)
}
