// Code generated by Kitex v0.7.3. DO NOT EDIT.

package articleservice

import (
	"context"
	article "github.com/Yra-A/Fusion_Go/kitex_gen/article"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ArticleList(ctx context.Context, req *article.ArticleListRequest, callOptions ...callopt.Option) (r *article.ArticleListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kArticleServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kArticleServiceClient struct {
	*kClient
}

func (p *kArticleServiceClient) ArticleList(ctx context.Context, req *article.ArticleListRequest, callOptions ...callopt.Option) (r *article.ArticleListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ArticleList(ctx, req)
}
