server:
	cd ../.. && kitex -module github.com/Yra-A/Fusion_Go idl/article.thrift
	kitex -module github.com/Yra-A/Fusion_Go -service ArticleService -use github.com/Yra-A/Fusion_Go/kitex_gen ../../idl/article.thrift