server:
	cd ../.. && kitex -module github.com/Yra-A/Fusion_Go idl/contest.thrift
	kitex -module github.com/Yra-A/Fusion_Go -service ContestService -use github.com/Yra-A/Fusion_Go/kitex_gen ../../idl/contest.thrift
