// Code generated by hertz generator.

package api

import (
	"github.com/Yra-A/Fusion_Go/cmd/api/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/gzip"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{gzip.Gzip(gzip.DefaultCompression)}
}

func _fusionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contestinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contestlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _info0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfouploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _profileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userprofileinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upload0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userprofileuploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}
