server:
	cd ../.. && kitex -module github.com/Yra-A/Fusion_Go idl/user.thrift
	kitex -module github.com/Yra-A/Fusion_Go -service UserService -use github.com/Yra-A/Fusion_Go/kitex_gen ../../idl/user.thrift
