server:
	cd ../.. && kitex -module github.com/Yra-A/Fusion_Go idl/team.thrift
	kitex -module github.com/Yra-A/Fusion_Go -service TeamService -use github.com/Yra-A/Fusion_Go/kitex_gen ../../idl/team.thrift
